stages:
  - test

test-all:
  stage: test
  image: node:20
  tags:
    - geocontrol
  before_script:
    - npm ci
  script:
    - npm run test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "delivery"'
      when: always
  artifacts:
    when: always
    reports:
      junit: reports/junit/jest-results.xml
    expire_in: 1 week
  allow_failure: false
